### ISSUE TITLE
unexpected error error_class=AMQ::Protocol::FrameTypeError

### ISSUE THREAD

**Issue by g2doug** [giraffi/fluent-plugin-amqp#53] opened 2018-05-01 17:29 UTC
unexpected error error_class=AMQ::Protocol::FrameTypeError error="Must be one of [:method, :headers, :body, :heartbeat]

I googled the error and got the test suite associated with [amq-protocol gem](https://github.com/ruby-amqp/amq-protocol/blob/master/spec/amq/protocol/frame_spec.rb)

**Comment by warmfusion** [comment] 2018-05-01 21:43
Interesting, what were you doing at the time to force such an issue?

Can you tell me what `gem list` shows and which versions of fluent and ruby are being used?

Can you provide the configuration you're using and perhaps even an example message being processed by the fluent pipeline?

**Comment by warmfusion** [comment] 2018-05-01 22:31
Fantastic, I'll try and take a look at whats going on, but I've not updated to latest versions for a few of these components so it might take a little while to debug...

**Comment by warmfusion** [comment] 2018-05-01 23:08
Based on the port, I'm thinking you're using Apache ActiveMQ as your message broker. Some quick research suggests that ActiveMQ supports amqp protocol version 1.0 which the bunny/ruby-amqp libraries do not support.[1]

Furthermore it looks like almost all client integrations to ActiveMQ are using either OpenWire or Stomp as their protocol of choice[2] with only a few client implementations around[3]

⚠️ Looking deeper at port 61616 I find that its infact an OpenWire protocol port, which this fluent-plugin won't work with at all... OpenWire is a binary protocol and I can't find any ruby support for it. Stomp however is much better supported but lower performance (and considerably fewer features compared to Rabbitmq and AMQP 0.9.1)

I'm afraid I'm going to have to mark this as a WontFix as my triage suggests the issue is a result of using Apache ActiveMQ and the OpenWire protocol, neither of which can be supported by the libraries this plugin is using and no appropriate alternatives exist.

Sorry

1. https://github.com/ruby-amqp/bunny/issues/304
2. http://activemq.apache.org/cross-language-clients.html
3. https://github.com/rabbitmq/rabbitmq-amqp1.0#clients-we-have-tested

**Closed by warmfusion** 2018-05-01 23:08 UTC
